package com.company.rapidclipse.demo.dragdrop.ui;

import com.vaadin.event.dd.DragAndDropEvent;
import com.vaadin.event.dd.DropHandler;
import com.vaadin.event.dd.acceptcriteria.AcceptAll;
import com.vaadin.event.dd.acceptcriteria.AcceptCriterion;
import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.ui.AbsoluteLayout.ComponentPosition;
import com.vaadin.ui.DragAndDropWrapper;
import com.vaadin.ui.DragAndDropWrapper.DragStartMode;
import com.vaadin.ui.DragAndDropWrapper.WrapperTargetDetails;
import com.vaadin.ui.DragAndDropWrapper.WrapperTransferable;
import com.xdev.ui.XdevAbsoluteLayout;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevPanel;
import com.xdev.ui.XdevView;

public class WndUIComponentDragDrop extends XdevView {

	/**
	 * 
	 */
	public WndUIComponentDragDrop() {
		super();
		this.initUI();

		this.absoluteLayout.setWidth("100%");
		this.absoluteLayout.setHeight("600px");

		//Create a dragable component(XdevButton)
		final DragAndDropWrapper buttonWrap = new DragAndDropWrapper(new XdevButton("Drag Me"));
		buttonWrap.setDragStartMode(DragStartMode.COMPONENT);
		buttonWrap.setSizeUndefined();
		
		//Create a dragable component(XdevButton)
		final DragAndDropWrapper buttonWrap2 = new DragAndDropWrapper(new XdevButton("Drag Me"));
		buttonWrap2.setDragStartMode(DragStartMode.COMPONENT);
		buttonWrap2.setSizeUndefined();
		
		//Create a dragable component(XdevButton)
		final DragAndDropWrapper buttonWrap3 = new DragAndDropWrapper(new XdevButton("Drag Me"));
		buttonWrap3.setDragStartMode(DragStartMode.COMPONENT);
		buttonWrap3.setSizeUndefined();
		
		//Create a dragable component(XdevButton)
		final DragAndDropWrapper buttonWrap4 = new DragAndDropWrapper(new XdevButton("Drag Me"));
		buttonWrap4.setDragStartMode(DragStartMode.COMPONENT);
		buttonWrap4.setSizeUndefined();
		
		//Add this dragable components to the absolutLayout
		this.absoluteLayout.addComponent(buttonWrap, "left:20px; top:20px");
		this.absoluteLayout.addComponent(buttonWrap2, "left:120px; top:20px");
		this.absoluteLayout.addComponent(buttonWrap3, "left:220px; top:20px");
		this.absoluteLayout.addComponent(buttonWrap4, "left:320px; top:20px");

		//Transform the absolutLayout to a dropable component
		final DragAndDropWrapper layoutWrapper = new DragAndDropWrapper(this.absoluteLayout);

		layoutWrapper.setDropHandler(new DropHandler() {

			@Override
			public AcceptCriterion getAcceptCriterion() {
				// TODO Auto-generated method stub
				return AcceptAll.get();
			}

			@Override
			public void drop(final DragAndDropEvent event) {
				// TODO Auto-generated method stub

				// Get the source and target component
				final WrapperTransferable dragComponent = (WrapperTransferable) event.getTransferable();
				final WrapperTargetDetails targetComponent = (WrapperTargetDetails) event
						.getTargetDetails();

				// Calculate the drag coordinate difference
				final int xChange = targetComponent.getMouseEvent().getClientX()
						- dragComponent.getMouseDownEvent().getClientX();
				final int yChange = targetComponent.getMouseEvent().getClientY()
						- dragComponent.getMouseDownEvent().getClientY();

				// Move the component in the absolute layout
				final ComponentPosition pos = WndUIComponentDragDrop.this.absoluteLayout.getPosition(dragComponent.getSourceComponent());
				pos.setLeftValue(pos.getLeftValue() + xChange);
				pos.setTopValue(pos.getTopValue() + yChange);
			}
		});

		this.panel.setContent(layoutWrapper);
	}

	@Override
	public void enter(final ViewChangeListener.ViewChangeEvent event) {
		super.enter(event);

	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.panel = new XdevPanel();
		this.absoluteLayout = new XdevAbsoluteLayout();
	
		this.absoluteLayout.setSizeFull();
		this.panel.setContent(this.absoluteLayout);
		this.panel.setSizeFull();
		this.setContent(this.panel);
		this.setSizeFull();
	} // </generated-code>

	// <generated-code name="variables">
	private XdevAbsoluteLayout absoluteLayout;
	private XdevPanel panel;
	// </generated-code>

}
